name: Build and release batBelt - Linux

on:
  push:
    tags:
      - v*

jobs:
  release-binary:
    name: Release batBelt linux binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: 'x64'

      - name: build and test batBelt
        working-directory: batbelt
        run: |
          pip install pyoxidizer
          pyoxidizer build --release install --target-triple x86_64-unknown-linux-musl
          cd ./build/x86*/release/
          mv install batbelt-linux-amd64
          tar -czf batbelt-linux-amd64.tar batbelt-linux-amd64
          mv batbelt-linux-amd64.tar ../../../
          ./batbelt-linux-amd64/batbelt
          ./batbelt-linux-amd64/batbelt serve --help

      - name: Create Release
        id: create_release
        continue-on-error: true
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: Upload linux binary to release
        if: always()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          file: ./batbelt/batbelt-linux-amd64.tar
          asset_name: batbelt-linux-amd64.tar
          tag: ${{ github.ref }}
          overwrite: true
          
